<?php
namespace Hrgruri\Icd3\Model;

use Hrgruri\Rarcs\NishikieClient as Client;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-20 at 01:08:00.
 */
class NishikieTest extends \PHPUnit_Framework_TestCase
{
    protected $nishikie;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $settings = (require __DIR__ . '/../../src/settings.php')['settings'];
        $capsule = new \Illuminate\Database\Capsule\Manager;
        $capsule->addConnection($settings['db']);
        $capsule->setAsGlobal();
        $capsule->bootEloquent();
        $this->nishikie = new Nishikie($capsule);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testExistsAsset()
    {
        $method = new \ReflectionMethod(get_class($this->nishikie), 'existsAsset');
        $method->setAccessible(true);
        $result = $method->invoke($this->nishikie, 'arcUP2976');
        $this->assertInternalType('boolean', $result);
    }

    public function testExistsInfo()
    {
        $method = new \ReflectionMethod(get_class($this->nishikie), 'existsInfo');
        $method->setAccessible(true);
        $result = $method->invoke($this->nishikie, 'arcUP2976');
        $this->assertInternalType('boolean', $result);
    }

    public function testGetDB()
    {
        $method = new \ReflectionMethod(get_class($this->nishikie), 'getDB');
        $method->setAccessible(true);
        $result = $method->invoke($this->nishikie, 'nishikie');
        $this->assertInternalType('int', $result);
    }

    public function testInsertAsset()
    {
        $target = 'arcUP2976';
        $method = new \ReflectionMethod(get_class($this->nishikie), 'insertAsset');
        $method->setAccessible(true);
        $result = $method->invoke($this->nishikie, $target);
        $this->assertInternalType('int', $result);
        $this->assertEquals(
            $method->invoke($this->nishikie, $target),
            $result
        );
    }

    public function testInfoMethod()
    {
        $target = 'arcUP2976';

        /*  insertInfo() */
        $method = new \ReflectionMethod(get_class($this->nishikie), 'insertInfo');
        $method->setAccessible(true);
        $insert_asset = $method->invoke($this->nishikie, $target);

        /*  selectInfot() */
        $method = new \ReflectionMethod(get_class($this->nishikie), 'selectInfo');
        $method->setAccessible(true);
        $select_asset = $method->invoke($this->nishikie, $target);

        $this->assertInstanceOf(\Hrgruri\Rarcs\Asset\Nishikie::class, $insert_asset);
        $this->assertInstanceOf(\Hrgruri\Rarcs\Asset\Nishikie::class, $select_asset);
        $this->assertEquals($insert_asset->id,      $select_asset->id);
        $this->assertEquals($insert_asset->title,   $select_asset->title);
        $this->assertEquals($insert_asset->artist,  $select_asset->artist);
        $this->assertEquals($insert_asset->url,     $select_asset->url);
        $this->assertEquals($insert_asset->cover,   $select_asset->cover);
    }
}
